tutorial/contacts/urls.py
from django.conf.urls import url, include

from . import views

from rest_framework import routers
import restviews


app_name = "contacts"


router = routers.DefaultRouter()
router.register(r"contacts", restviews.ContactViewSet)


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contacts/', views.create, name='create'),
    url(r'^(?P<contact_id>[0-9]+)/$', views.read, name='read'),
    url(r'^(?P<contact_id>[0-9]+)/update$', views.update, name='update'),
    url(r'^(?P<contact_id>[0-9]+)/delete$', views.delete, name='delete'),

    #rest
    url(r'^rest/', include(router.urls)),
]

tutorial/tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

    url(r'^contacts/', include('contacts.urls')),
    url(r'^admin/', admin.site.urls),
]

tutorial/contacts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Contact(models.Model):
    id = models.AutoField(primary_key= True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    phone=models.IntegerField()

    class Meta:
        unique_together = ('first_name', 'last_name',)

    def __unicode__(self):
        return self.first_name + " " + self.last_name + " - " + str(self.phone)

tutorial/quickstart/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

tutorial/contacts/views.py
from django.shortcuts import render

# Create your views here.

from .models import Contact
from django.template import loader
from django.contrib.auth import authenticate, login, logout

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


def index(request):
    contacts_list = Contact.objects.all()

    template = loader.get_template('contacts/index.html')
    context = {
        'contacts_list': contacts_list,
    }
    return HttpResponse(template.render(context, request))

def create(request):

    first_name = request.POST['first_name']
    last_name = request.POST['last_name']

    phone = request.POST['phone']

    contact = Contact.objects.create(first_name=first_name, last_name=last_name, phone=phone)

    contact.save()

    print "Created a  contact with id ", contact.id
    return HttpResponseRedirect(reverse('contacts:index'))
    pass

def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id)

    print "in update contact is ",contact

    first_name = request.POST['first_name']
    last_name = request.POST['last_name']

    phone = request.POST['phone']

    contact.first_name = first_name
    contact.last_name = last_name
    contact.phone = phone

    contact.save()
    print "Updated the contact for id ",contact_id
    return HttpResponseRedirect(reverse('contacts:index'))
    pass

def delete(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id)

    contact.delete()

    print "Deleted the contact for id ", contact_id
    return HttpResponseRedirect(reverse('contacts:index'))
    pass

def read(request, contact_id):
    contact = Contact.objects.get(id=contact_id)
    print "contact in read ",contact
    template = loader.get_template('contacts/details.html')
    context = {
        'contact': contact,
    }
    return HttpResponse(template.render(context, request))
    pass

tutorial/quickstart/views.py
from django.shortcuts import render

# Create your views here.

tutorial/contacts/templates/contacts/base.html
:
{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}  <a href="{% url 'contacts:logout' %}">[logout]</a></p>
{% else %}
    <p>Welcome, Guest <a href="{% url 'contacts:login' %}">[login]</a></p>
{% endif %}
:

tutorial/contacts/templates/contacts/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if contact %}
    <form action="{% url 'contacts:update' contact.id %}" method="post">
    {% csrf_token %}
        <input type="text" name="first_name" id="first_name" value="{{ contact.first_name }}" />
        <input type="text" name="last_name" id="last_name" value="{{ contact.last_name }}" />
        <input type="text" name="phone" id="phone" value="{{ contact.phone }}" />

        <input type="submit" value="edit" />
</form>

    <form action="{% url 'contacts:delete' contact.id %}" method="put">
    {% csrf_token %}

        <input type="submit" value="delete" />
</form>
{% else %}
    <p>No contact is available.</p>
{% endif %}
</body>
</html>

tutorial/contacts/templates/contacts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contacts</title>
</head>
<body>
{% if contacts_list %}
    <ul>
    {% for contact in contacts_list %}
        <li><a href="/contacts/{{ contact.id }}/">{{ contact.first_name }} {{  contact.last_name }} -- Ph: {{ contact.phone }}</a></li>
    {% endfor %}
    </ul>
{% endif %}


<form action="{% url 'contacts:create' %}" method="post">
    {% csrf_token %}
        <input type="text" name="first_name" id="first_name" placeholder="Enter First name" />
        <input type="text" name="last_name" id="last_name" placeholder="Enter Last name" />
        <input type="text" name="phone" id="phone" placeholder="Enter phone number" />

        <input type="submit" value="create" />
    </form>
</body>
</html>

tutorial/contacts/templates/contacts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'contacts:contacts_login' %}" method="post">
    {% csrf_token %}
        <input type="text" name="username" id="username" placeholder="Enter user name" />
        <input type="password" name="password" id="password" placeholder="Enter password" />

        <input type="submit" value="login" />
    </form>

</body>
</html>